### PR TITLE
[TASK] Update to latest m2 release

### PR DESCRIPTION
**Pull request by therouv**
And again :-)

### CODE REVIEW

**Comment by rgranadino** [comment]
Would you be interested in having write access/added to the repo for these changes? :)

**Comment by rgranadino** [comment]
I'm also tempted to try and modify but not sure if that's a great idea either.

**Comment by therouv** [comment]
@rgranadino Would love the write access to add those changes "faster". Automating this would be great to! :-)

**Comment by rgranadino** [comment]
Just added you as a collaborator, thanks again for helping out.

**Pull request merged**
