### PR TITLE
Added nfs for synced folder on OSX

### PR DESCRIPTION
**Pull request by tonegolf71**
Enabled NFS for OSX as this greatly improves performance

### CODE REVIEW

**Comment by rgranadino** [comment]
Hi @tonegolf71, thanks for the PR. The performance is awful when using Virtual Box's shared directory. Unfortunately it's the only mechanism that will work cross platform "consistently", albeit poorly/unusable. 

From the vagrant docs: 

> Vagrant will ignore your request for NFS synced folders on Windows. 

The SMB option is only supported on Windows hosts and the latest option, rsync, is only supported on hosts that have rsync installed. It's option for Windows but only if the user has an `rsync.exe` in their PATH. It's also only available as part of later versions of Vagrant.

Given the state of affairs I'm torn as to which solution to go with. I'm leaning towards the `rsync` since it at least is *possible* to get working in Windows and should work out of the box for *nix and OS X users.

Do you have any experience with using the rsync option? I haven't had a chance to test how well it behaves just yet. 

Another idea I had was to just update the `README` and include a big warning suggestion users change the sync behavior to match their system (NFS or SMB).

**Comment by tonegolf71** [comment]
Hi,

The code I've added will actually only use NFS for non-Windows operating systems, `if Vagrant::Util::Platform.windows?`, so this change will not impact Windows people and you get compatibility for everyone.

Using Rsync means you are copying the files in to the VM which does work faster for page loads, but the auto-update mode in vagrant to rsync the files across is too slow in my opinion and you end up refreshing many times waiting for the files to update.

If you are looking to keep this compatible for everyone I would recommend the approach in the pull request, if you are looking for the best possible performance for yourself it would be worth trying the Rsync method and maybe playing with your IDE to see if it can SCP the files in to your VM on save (PHPStorm supports this).

Hope that helps.

**Comment by rgranadino** [comment]
Hi @tonegolf71, I apologize for not reading the changed Vagrant file more closely and being a newb when it comes to the capabilities of Vagrant. Your change seems like the better approach, thanks for the PR!

**Comment by tonegolf71** [comment]
No probs, thanks for sharing your work!

**Pull request merged**
